SOURCECODE-original_PROBu/MVCIdentityConfirm/Controllers/RatingController.cs
using MVCIdentityConfirm.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.IO;
using System.Drawing;
using System.Web;
using MVCIdentityConfirm.Necessary;

namespace MVCIdentityConfirm.Controllers
{
    public class RatingController : Controller
    {
        // GET: Rating
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult RatPrzelozony(int id)
        {
            dataDB dt = new dataDB();
            ocenaPrzelozony oc = new ocenaPrzelozony();
            string userId = User.Identity.GetUserId().ToString();
            var manager = dt.Przelozony.Where(x => x.Id == id).Select(y => y).FirstOrDefault();
            var manWydz = dt.Wydzial.Where(z => z.PrzelozonyId == id).Select(h => h).FirstOrDefault();
            var manFirma = dt.Company.Where(v => v.Id == manWydz.CompanyID).Select(s => s).FirstOrDefault();
            var ocenaGet = dt.ocenaPrzelozony.Where(a => a.przelozonyId == id && a.userId == userId).Select(m => m).FirstOrDefault();
            if (ocenaGet != null) {
                oc = ocenaGet;
            }
            else
            {
                oc.userId = "0";
                oc.przelozonyId = 0;
                oc.kulturaOs = 50;
                oc.inteligencja = 50;
                oc.cwaniastwo = 50;
                oc.przyznanieBlad = 50;
                oc.radzenieKrytyka = 50;
                oc.rzetenaWiedza = 50;
                oc.udzielaniePochwal = 50;
                oc.umieKomunikowania = 50;
                oc.umiSluchania = 50;
            }
            managerInfo mag = new managerInfo();

            mag.imie = manager.Imie;
            mag.nazwisko = manager.Nazwisko;
            mag.stanowisko = manager.Stanowisko;
            mag.wydzial = manWydz.Wydzial1;
            mag.firma = manFirma.CompanyName;
            mag.id = manager.Id;
            mag.oceny = oc;
            mag.companyId = manFirma.Id;

            return View(mag);
        }
         
        public ActionResult rateCompany(int id, int? przelozony)
        {
            dataDB dta = new dataDB();
            string userId = User.Identity.GetUserId();
            var oc = dta.ocenaCompany.Where(x => x.companyId == id && x.userId == userId).Select(y => y).FirstOrDefault();
            var infoComp = dta.Company.Where(z => z.Id == id).Select(v => v).FirstOrDefault();
            ocenaCompanyModel ocenaModel = new ocenaCompanyModel();
            ocenaCompany ocenaC = new ocenaCompany();

            if(oc != null)
            {
                ocenaC = oc;
            }else
            {
                ocenaC.atmosfera = 50;
                ocenaC.awans = 50;
                ocenaC.companyId = 0;
                ocenaC.dodatki = 50;
                ocenaC.ksztalcenie = 50;
                ocenaC.mobbing = 50;
                ocenaC.uklady_ = 50;
                ocenaC.userId = "0";
                ocenaC.uznanie = 50;
                ocenaC.zarobki = 2500;
                ocenaC.socjal = 50;
                ocenaC.stres = 50;
            }

            ocenaModel.companyID = infoComp.Id;
            ocenaModel.companyName = infoComp.CompanyName;
            ocenaModel.adres = infoComp.Ulica + ", " + infoComp.Miejscowosc;
            ocenaModel.ocena = ocenaC;
            ocenaModel.userId = userId;
            if (przelozony != null)
            {
                ocenaModel.przelozonyId = przelozony;
            }else
            {
                ocenaModel.przelozonyId = 0;
            }

            return View(ocenaModel);
        }


        public JsonResult saveRatingCompany (int company, int[] data)
        {
            string userId = User.Identity.GetUserId();
            dataDB dta = new dataDB();
            var check = dta.ocenaCompany.Where(x => x.companyId == company && x.userId == userId).Select(y => y);

            var rate = dta.ratingCompany.Where(g => g.companyId == company).Select(z => z).FirstOrDefault();

            if (check.Count() != 0)
            {
                var update= dta.ocenaCompany.Where(x => x.companyId == company && x.userId == userId).Select(y => y).FirstOrDefault();
                var rte = dta.ratingCompany.Where(b => b.companyId == company).Select(m => m).FirstOrDefault();

                if (rte != null)
                {
                    rte.atmosfera -= update.atmosfera;
                    rte.awans -= update.awans;
                    rte.dodatki -= update.dodatki;
                    rte.ksztalcenie -= update.ksztalcenie;
                    rte.mobbing -= update.mobbing;
                    rte.socjal -= update.socjal;
                    rte.stres -= update.stres;
                    rte.uklady -= update.uklady_;
                    rte.uznanie -= update.uznanie;
                    rte.zarobki -= update.zarobki;
                    rte.ogolnyWynik -= update.zarobki + update.uznanie + update.uklady_ + update.stres + update.socjal + update.mobbing + update.ksztalcenie + update.dodatki + update.awans + update.atmosfera;
                }

                update.atmosfera = data[0];
                update.awans = data[1];
                update.dodatki = data[2];
                update.ksztalcenie = data[3];
                update.mobbing = data[4];
                update.uklady_ = data[5];
                update.uznanie = data[6];
                update.zarobki = data[7];
                update.socjal = data[8];
                update.stres = data[9];

                
                rte.atmosfera += data[0];
                rte.awans += data[1];
                rte.dodatki += data[2];
                rte.ksztalcenie += data[3];
                rte.mobbing += data[4];
                rte.socjal += data[8];
                rte.stres += data[9];
                rte.uklady += data[5];
                rte.uznanie += data[6];
                rte.zarobki += data[7];
                rte.ogolnyWynik += data.Sum();

                dta.SaveChanges();

            }
            else
            {
                ocenaCompany oc = new ocenaCompany();
                oc.atmosfera = data[0];
                oc.awans = data[1];
                oc.dodatki = data[2];
                oc.ksztalcenie = data[3];
                oc.mobbing = data[4];
                oc.uklady_ = data[5];
                oc.uznanie = data[6];
                oc.zarobki = data[7];
                oc.socjal = data[8];
                oc.stres = data[9];
                oc.userId = userId;
                oc.companyId = company;

                dta.ocenaCompany.Add(oc);

                if (rate != null)
                {
                    
                    rate.companyId = company;
                    rate.atmosfera += data[0];
                    rate.awans += data[1];
                    rate.dodatki += data[2];
                    rate.ksztalcenie += data[3];
                    rate.mobbing += data[4];
                    rate.uklady += data[5];
                    rate.uznanie += data[6];
                    rate.zarobki += data[7];
                    rate.socjal += data[8];
                    rate.stres += data[9];
                    rate.ogolnyWynik += data.Sum();
                    rate.liczbaVoice += 1;
                }else
                {
                    
                    ratingCompany rt = new ratingCompany();
                    rt.atmosfera = data[0];
                    rt.awans = data[1];
                    rt.dodatki = data[2];
                    rt.ksztalcenie = data[3];
                    rt.mobbing = data[4];
                    rt.uklady = data[5];
                    rt.uznanie = data[6];
                    rt.zarobki = data[7];
                    rt.socjal = data[8];
                    rt.stres = data[9];
                    rt.companyId = company;
                    rt.liczbaVoice = 1;
                    rt.ogolnyWynik = data.Sum() ;

                    dta.ratingCompany.Add(rt);
                }

                dta.SaveChanges();
                

            }

            return Json(JsonRequestBehavior.AllowGet);
        }


        public JsonResult saveRating(int idPrzelozony, int[] dane)
        {
            string userId = User.Identity.GetUserId().ToString();
            dataDB dt = new dataDB();
            var checkExist = dt.ocenaPrzelozony.Where(g => g.przelozonyId == idPrzelozony && g.userId == userId).Select(c => c);
            
            if (checkExist.Count() != 0)
            {
                var check = dt.ocenaPrzelozony.Where(g => g.przelozonyId == idPrzelozony && g.userId == userId).Select(c => c).FirstOrDefault();
                check.userId = userId;
                check.przelozonyId = idPrzelozony;
                check.kulturaOs = dane[0];
                check.inteligencja = dane[1];
                check.umiSluchania = dane[2];
                check.przyznanieBlad = dane[3];
                check.cwaniastwo = dane[4];
                check.udzielaniePochwal = dane[5];
                check.umieKomunikowania = dane[6];
                check.radzenieKrytyka = dane[7];
                check.rzetenaWiedza = dane[8];

                dt.SaveChanges();
            }else
            {
                ocenaPrzelozony op = new ocenaPrzelozony();

                op.userId = userId;
                op.przelozonyId = idPrzelozony;
                op.kulturaOs = dane[0];
                op.inteligencja = dane[1];
                op.umiSluchania = dane[2];
                op.przyznanieBlad = dane[3];
                op.cwaniastwo = dane[4];
                op.udzielaniePochwal = dane[5];
                op.umieKomunikowania = dane[6];
                op.radzenieKrytyka = dane[7];
                op.rzetenaWiedza = dane[8];


                dt.ocenaPrzelozony.Add(op);
                dt.SaveChanges();
            }

SOURCECODE-original_PROBu/MVCIdentityConfirm/Views/Rating/RatPrzelozony.cshtml
@model MVCIdentityConfirm.Models.managerInfo



<link href="~/Content/slidery/slideControl.css" rel="stylesheet" />
<link href="~/Content/slidery/jquery.ui-slider.css" rel="stylesheet" />
<script src="~/Content/slidery/jquery.slideControl.js"></script>
<script src="~/Content/slidery/jquery.ui-slider.js"></script>


<link href="~/Content/slidery/jquery.range.css" rel="stylesheet" />
<script src="~/Content/slidery/jquery.range.js"></script>




<div class="lightBlue">
    <div style="padding-top:30px; margin-left: 20px;" id="x" class="comp">
        <h4 id="@Model.id" class="przelozonyClass" style="font-size: 16px;"> Oceń Pana \ Panią <span style="color:firebrick"> @Model.imie @Model.nazwisko </span> zajmującego stanowisko <span style="color: #808080">@Model.stanowisko </span>  w firmie <span style="color: #808080"> @Model.firma</span> w skali od 1 do 100.</h4>
    </div>
    <br/>


    <div style="float:left;">
        <div style="margin-left: 20px; "> <p id="value" style="color:#e5e5e5"> Kultura osobista: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Inteligencja: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Umiejętność słuchania: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Przyznanie do błędu: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Cwaniactwo: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Umiejętność udzielania pochwał: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Umiejętność efektywnego komunikowania: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Radzenie sobie z krytyką: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Rzetelna wiedza: </p></div>
    </div>


    <div style="float:left;">
        <div style="padding-top:7px; margin-left: 50px;">
            <input class="single-slider theme-blue" type="hidden" value="@Model.oceny.kulturaOs" id="kultura">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.oceny.inteligencja" id="inteligencja">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.oceny.umiSluchania" id="sluchanie">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.oceny.przyznanieBlad" id="bledu">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.oceny.cwaniastwo" id="cwaniactwo">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.oceny.udzielaniePochwal" id="pochwaly">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.oceny.umieKomunikowania" id="komunikowanie">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.oceny.radzenieKrytyka" id="krytyka">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.oceny.rzetenaWiedza" id="rzetelnaWiedza">
        </div>
    </div>

    <div style="clear:both"></div>


    <div>
        <div style="padding-top:10px;">
            <input type="button" value="ZAPISZ OCENĘ" class="btnNew paper paper-curl-right" id="zatwierdz" style="float:left; margin-left: 20px; outline: none" />

        </div>
        <div style="padding-top:10px;">
            <a href="#" id="anuluj">
                <h5   style="float:left; margin-left: 20px; outline: none">ANULUJ</h5>
            </a>
        </div>

    </div>
</div>
<div class="modal fade" id="PotwZapis" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="text-align: center; overflow-y:hidden;">
    <div class="modal-dialog" style="width:300px; text-align: center; margin-top: 250px;">
        <div class="modal-content" style="width:300px; text-align: center;">
            <div class="modal-body" style="background-color: #182026; width:300px; text-align: center;">
                <h4 style="color: firebrick; text-align: center;">Dane zostały zapisane.</h4>
            </div>

        </div>
    </div>
</div>
<script>

    $(function () {
        
        $("#zatwierdz").click(function () {
            

            var dane = new Array(8);
            dane[0] = $("#kultura").val();
            dane[1] = $("#inteligencja").val();
            dane[2] = $("#sluchanie").val();
            dane[3] = $("#bledu").val();
            dane[4] = $("#cwaniactwo").val();
            dane[5] = $("#pochwaly").val();
            dane[6] = $("#komunikowanie").val();
            dane[7] = $("#krytyka").val();
            dane[8] = $("#rzetelnaWiedza").val();
            $.ajax({
                url: '@Url.Action("saveRating", "Rating")',
                dataType: "json",
                type: "POST",
                traditional: true,
                data: { "idPrzelozony": $(".przelozonyClass").attr("id"), "dane": dane },
                success: function (dta) {
                    $("#PotwZapis").modal("show");
                    setTimeout(function () {
                        $("#PotwZapis").modal("hide");
                        var adres = '@Url.Action("Index", "Home", new { powrot = "-555" })';
                        adres = adres.replace("-555", $(".przelozonyClass").attr("id"));
                        window.location = adres;
                    }, 2000);
                    
                }
            });
        });
    });
    $(function () {

        $("#anuluj").click(function () {
            var adres = '@Url.Action("Index", "Home", new { powrot = "-555" })';
            adres = adres.replace("-555", $(".przelozonyClass").attr("id"));
            window.location = adres;
        });
    });

        $('.single-slider').jRange({
            from: 0,
            to: 100,
            scale: [],
            theme: 'theme-blue',

        });

        $('.single-slider').jRange().val();


        //    var position = 50;

        //$('#ui-nowy')
        //    .UISlider({
        //        min: 1,
        //        max: 100,
        //        value: position,
        //        smooth: false

        //    })
        //    .on('drag', function (event, value) {

        //        $('#value').text(value);

        //    });

        //    $('#value').text(position);


</script>

SOURCECODE-original_PROBu/MVCIdentityConfirm/Views/Rating/rateCompany.cshtml
@model MVCIdentityConfirm.Models.ocenaCompanyModel



<link href="~/Content/slidery/slideControl.css" rel="stylesheet" />
<link href="~/Content/slidery/jquery.ui-slider.css" rel="stylesheet" />
<script src="~/Content/slidery/jquery.slideControl.js"></script>
<script src="~/Content/slidery/jquery.ui-slider.js"></script>


<link href="~/Content/slidery/jquery.range.css" rel="stylesheet" />
<script src="~/Content/slidery/jquery.range.js"></script>

<div class="lightBlue">
    <div style="padding-top:30px; margin-left: 20px;" id="@Model.companyID" class="cid">
        <h4 id="@Model.przelozonyId" class="przelozonyClass" style="font-size: 16px;"> Oceń warunki pracy panujące w firmie <span style="color:firebrick"> @Model.companyName</span> ( @Model.adres) w skali od 1 do 100.</h4>
    </div>
    <br />

    <div style="float:left">
        <div style="margin-left: 20px; "> <p id="value" style="color:#e5e5e5"> Atmosfera: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Awans: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Dodatki: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Kształcenie: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Mobbing: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Układy: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Uznanie: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Zarobki: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Socjal: </p></div>
        <div class="nameSliderSpace"> <p id="value" style="color:#e5e5e5"> Stres: </p></div>
    </div>



    <div  style="float:left">
        <div style="padding-top:7px; margin-left: 50px;">
            <input class="single-slider theme-blue" type="hidden" value="@Model.ocena.atmosfera" id="Atmosfera">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.ocena.awans" id="Awans">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.ocena.dodatki" id="Dodatki">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.ocena.ksztalcenie" id="Kształcenie">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.ocena.mobbing" id="Mobbing">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.ocena.uklady_" id="Układy">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.ocena.uznanie" id="Uznanie">
        </div>
        <div class="sliderSpace">
            <input class="money-slider theme-blue" type="hidden" value="@Model.ocena.zarobki" id="Zarobki">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.ocena.socjal" id="Socjal">
        </div>
        <div class="sliderSpace">
            <input class="single-slider theme-blue" type="hidden" value="@Model.ocena.stres" id="Stres">
        </div>
    </div>

    <div style="clear:both;"></div>
    <div>
        <div style="padding-top:10px;">
            <input type="button" value="ZAPISZ OCENĘ" class="btnNew paper paper-curl-right" id="zatwierdz" style="float:left; margin-left: 20px; outline: none" />

        </div>
        <div style="padding-top:10px;">
            <a href="#" id="anuluj">
                <h5 style="float:left; margin-left: 20px; outline: none">ANULUJ</h5>
            </a>
        </div>

    </div>
</div>
<div class="modal fade" id="PotwZapis" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="text-align: center; overflow-y:hidden;">
    <div class="modal-dialog" style="width:300px; text-align: center; margin-top: 250px;">
        <div class="modal-content" style="width:300px; text-align: center;">
            <div class="modal-body" style="background-color: #182026; width:300px; text-align: center;">
                <h4 style="color: firebrick; text-align: center;">Dane zostały zapisane.</h4>
            </div>

        </div>
    </div>
</div>
<script>

    function hideWydzial() {
        $(function () {

            $(".wydzialHide").hide();

        });
        $(function () {
            $("#copanyList").css({ height: "50vh" });
        });

    };


    hideWydzial();


    $(function () {

        $("#zatwierdz").click(function () {


            var dane = new Array(9);
            dane[0] = $("#Atmosfera").val();
            dane[1] = $("#Awans").val();
            dane[2] = $("#Dodatki").val();
            dane[3] = $("#Kształcenie").val();
            dane[4] = $("#Mobbing").val();
            dane[5] = $("#Układy").val();
            dane[6] = $("#Uznanie").val();
            dane[7] = $("#Zarobki").val();
            dane[8] = $("#Socjal").val();
            dane[9] = $("#Stres").val();
            $.ajax({
                url: '@Url.Action("saveRatingCompany", "Rating")',
                dataType: "json",
                type: "POST",
                traditional: true,
                data: { "company": $(".cid").attr("id"), "data": dane },
                success: function (dta) {
                    
                    $("#PotwZapis").modal("show");
                    setTimeout(function () {
                        $("#PotwZapis").modal("hide");
                        var adres = '@Url.Action("Index", "Home", new { powrot = "-555" })';
                        if ($(".przelozonyClass").attr("id") != 0) {
                            var adres = '@Url.Action("Index", "Home", new { powrot = "-555" })';
                            adres = adres.replace("-555", $(".przelozonyClass").attr("id"));
                        } else {
                            var adres = '@Url.Action("Index", "Home", new { cid = "-21243" })';
                            adres = adres.replace("-21243", $(".cid").attr("id"));
                        }
                        window.location = adres;

                        
                    }, 2000);

                }
            });
        });
    });

    $(function () {

        $("#anuluj").click(function () {
            var adres = '@Url.Action("Index", "Home", new { powrot = "-555", cid = "-21243" })';
            if ($(".przelozonyClass").attr("id") != 0) {
                var adres = '@Url.Action("Index", "Home", new { powrot = "-555" })';
                adres = adres.replace("-555", $(".przelozonyClass").attr("id"));
            } else { 
                var adres = '@Url.Action("Index", "Home", new { cid = "-21243" })';
                adres = adres.replace("-21243", $(".cid").attr("id"));
            }
            window.location = adres;
        });
    });

        $('.single-slider').jRange({
            from: 0,
            to: 100,
            scale: [],
            theme: 'theme-blue',

        });
        $('.money-slider').jRange({
            from: 0,
            to: 20000,
            scale: [],
            theme: 'theme-blue',

        });

        $('.single-slider').jRange().val();


        //    var position = 50;

        //$('#ui-nowy')
        //    .UISlider({
        //        min: 1,
        //        max: 100,
        //        value: position,
        //        smooth: false

        //    })
        //    .on('drag', function (event, value) {

        //        $('#value').text(value);

        //    });

        //    $('#value').text(position);


</script>



@{
    ViewBag.Title = " - Oceń firmę " + Model.companyName;
}